[package]
name = "metaboss_lib"
version = "0.3.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
borsh = "0.9.1"
bs58 = "0.4.0"
env_logger = "0.9.0"
glob = "0.3.0"
indicatif = { version = "0.16.2", features = ["rayon"] }
lazy_static = "1.4.0"
log = "0.4.14"
metaplex-token-metadata = "0.0.1"
num_cpus = "1.13.0"
ratelimit = "0.4.4"
rayon = "1.5.1"
reqwest = "0.11.5"
serde = "1.0.130"
serde_json = "1.0.68"
serde_yaml = "0.8.21"
solana-account-decoder = "1.8.0"
solana-client = "1.8.1"
solana-program = "1.8.0"
solana-sdk = "1.8.0"
spl-associated-token-account = "1.0.3"
spl-token = "3.2.0"
structopt = "0.3.23"
thiserror = "1.0.30"

[dev-dependencies]
assert_cmd = "2.0.2"