on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

name: Format and Compile Checks

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "Installing libudev-dev"
          sudo apt install libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "Installing libudev-dev"
          sudo apt-get install libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "Installing libudev-dev"
          sudo apt-get install libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "Installing libudev-dev"
          sudo apt-get install libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings